[package]
authors = ["Sean Bowe <ewillbefull@gmail.com>, CPerezz <carlos@dusk.network>"]
description = "Fork of the implementation of the BLS12-381 pairing-friendly elliptic curve construction with some extra tooling needed by the Dusk team"
documentation = "https://github.com/dusk-network/bls12_381"
homepage = "https://github.com/dusk-network/bls12_381"
license = "MIT/Apache-2.0"
name = "dusk-bls12_381"
repository = "https://github.com/dusk-network/bls12_381"
version = "0.4.0"
keywords = ["cryptography", "bls12_381", "zk-snarks", "ecc", "elliptic-curve"]
categories =["Algorithms", "Cryptography", "Development tools"]
edition = "2018"
exclude = [".github/workflows/ci.yml",
".gitignore", 
]

[dependencies]
byteorder = {version = "1.3.4", default-features = false}
rayon = "1.3.0"
serde = {version = "1.0.106", optional = true}
log = { version = "0.4.8" }
rand_core = "0.6"
canonical = {version = "0.4", optional = true}
canonical_derive = {version = "0.4", optional = true}

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[dev-dependencies]
criterion = "0.2.11"
bincode = "1"
rand = "0.8"

[[bench]]
name = "groups"
harness = false
required-features = ["groups"]

[dependencies.subtle]
version = "2.3.0"
default-features = false

[features]
default = ["groups", "pairings", "alloc", "std", "endo"]
groups = []
pairings = ["groups"]
alloc = []
nightly = ["subtle/nightly"]
std = ["alloc"]
canon = ["canonical", "canonical_derive"]
serde_req = ["serde", "std"]
endo = []
